---
galaxy_info:
  author: Steve Fulmer
  description: "Deploy VMs from templates with cloud-init"
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - proxmox
dependencies: []
