---
galaxy_info:
  author: Steve Fulmer
  description: >-
    Configure Proxmox Backup Server datastores and PVE backup jobs with prune/verify schedules
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - proxmox
    - backup
    - pbs
dependencies: []
