---
galaxy_info:
  author: Steve Fulmer
  description: >-
    Configure Proxmox VLANs, bridges, and SDN zones/vnets/subnets
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - proxmox
    - network
    - sdn
    - vlan
dependencies: []
