---
# defaults/main.yml for proxmox_network_setup

# Target host
proxmox_network_setup_host: ""

# Authentication
proxmox_network_setup_username: ""
proxmox_network_setup_password: ""
proxmox_network_setup_api_key: ""

# Behavior
proxmox_network_setup_validate_certs: true
proxmox_network_setup_state: present
