---
galaxy_info:
  author: Steve Fulmer
  description: >-
    Join Proxmox nodes to cluster, configure HA groups and resources
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - proxmox
    - cluster
    - ha
dependencies: []
